name: "Package application"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        default: 1.0.0
        required: true
jobs:
  package:
    strategy:
      matrix:
        go-version: [1.18.x]
        node-version: [18]
        platform: [ windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      ##### Initial setup #####
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install ubuntu libraries
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt install -y libgtk-3-dev
          sudo apt install -y libwebkit2gtk-4.0-dev
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      ##### Setup Environment ####
      - name: Setup environment
        shell: bash
        run: echo "RELEASE_FILE=$(jq -r .name wails.json)-${{ github.event.inputs.version }}-$(echo "${{ matrix.platform }}" | cut -d- -f1)-amd64.zip" >> $GITHUB_ENV
      ##### Build app #####
      - name: Build App
        run: wails build
      - name: Package App MacOS / Linux
        if: matrix.platform != 'windows-latest'
        run: cd build/bin && zip -r ../../${{ env.RELEASE_FILE }} *
      - name: Package App Windows
        if: matrix.platform == 'windows-latest'
        run: Compress-Archive -Path "$PWD\build\bin\*" -DestinationPath "$PWD\${{ env.RELEASE_FILE }}"
      ##### Upload artifacts #####
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.RELEASE_FILE }}
          asset_name: ${{ env.RELEASE_FILE }}
          tag: ${{ github.event.inputs.version }}